---
defaults:
  actions:
    queue:
      name: default
      method: rebase
      rebase_fallback: merge
      update_method: rebase

queue_rules:
  - name: default
    conditions:
      - "status-success=codespell"
      - "status-success=test and build (1.16)"
      - "status-success=lint"
      - "status-success=DCO"

pull_request_rules:
  - name: remove outdated approvals
    conditions:
      - base~=^(main)|(release-.+)$
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        # yamllint disable-line rule:truthy
        message: "This pull request now has conflicts with the target branch.
        Could you please resolve conflicts and force push the corrected
        changes? 🙏"
  - name: automatic merge
    conditions:
      - label!=DNM
      - base~=^(main)|(release-.+)$
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "status-success=codespell"
      - "status-success=test and build (1.16)"
      - "status-success=lint"
      - "status-success=DCO"
    actions:
      queue: {}
      dismiss_reviews: {}
      delete_head_branch: {}
  - name: automatic merge PR having ready-to-merge label
    conditions:
      - label!=DNM
      - label=ready-to-merge
      - base~=^(main)|(release-.+)$
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "status-success=codespell"
      - "status-success=test and build (1.16)"
      - "status-success=lint"
      - "status-success=DCO"
    actions:
      queue: {}
      dismiss_reviews: {}
      delete_head_branch: {}
  - name: backport patches to release v0.1 branch
    conditions:
      - base=main
      - label=backport-to-release-v0.1
    actions:
      backport:
        branches:
          - release-v0.1
