# permissions for end users to view volumereplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumereplication-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io.volumereplication.ocs.openshift.io
  resources:
  - volumereplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io.volumereplication.ocs.openshift.io
  resources:
  - volumereplications/status
  verbs:
  - get
