# permissions for end users to edit volumereplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumereplication-editor-role
rules:
- apiGroups:
  - ocs.openshift.io.volumereplication.ocs.openshift.io
  resources:
  - volumereplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocs.openshift.io.volumereplication.ocs.openshift.io
  resources:
  - volumereplications/status
  verbs:
  - get
