# permissions for end users to edit volumereplicas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumereplica-editor-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumereplicas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumereplicas/status
  verbs:
  - get
